title: Get Ready To TypeScript
tagline: TypeScript
description: Get Ready To TypeScript
template:
  repo: get-ready-to-typescript-template
  name: get-ready-to-typescript-exercise
before:
  - type: createIssue
    title: Welcome to the show!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
