title: Get Ready To TypeScript
tagline: TypeScript
description: Get Ready To TypeScript
template:
  repo: get-ready-to-typescript-template
  name: get-ready-to-typescript-exercise
before:
  - type: createIssue
    title: Welcome to the show!
    body: new-issue.md
steps:
  - title: Install Git
    description: Learn How To Install Git
    event: issues.closed
    link: '{{ repoUrl }}'
    actions:
      - type: createIssue
        title: Enjoy Installing Git
        body: install-git.md
steps:
  - title: Install NodeJS
    description: Learn How To Install NodeJS
    event: issues.closed
    link: '{{ repoUrl }}'
    actions:
      - type: createIssue
        title: Enjoy Installing NodeJS
        body: install-nodejs.md
